# Generated by Django 4.2.1 on 2023-05-22 12:29

from django.db import migrations, models
import django.db.models.deletion
import django_pkiman.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('level', models.CharField(choices=[('I', 'ИНФО'), ('W', 'Предупреждение'), ('E', 'Ошибка')], db_index=True, default='I', max_length=1)),
                ('message', models.TextField()),
            ],
            options={
                'verbose_name': 'Запись журнала',
                'verbose_name_plural': 'Журнал',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Proxy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('url', models.URLField(null=True)),
                ('username', models.CharField(blank=True, max_length=128, null=True)),
                ('password', models.CharField(blank=True, max_length=64, null=True)),
                ('is_default', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'verbose_name': 'Прокси-сервер',
                'verbose_name_plural': 'Прокси',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Crt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('subject_identifier', models.CharField(db_index=True, max_length=128, null=True)),
                ('issuer_identifier', models.CharField(max_length=128, null=True)),
                ('subject_dn', models.JSONField()),
                ('serial', models.CharField(max_length=128, verbose_name='серийный номер')),
                ('issuer_dn', models.JSONField()),
                ('issuer_serial', models.CharField(max_length=128, null=True)),
                ('fingerprint', models.CharField(max_length=64, unique=True)),
                ('file', models.FileField(upload_to=django_pkiman.models.get_upload_file_path)),
                ('valid_after', models.DateTimeField()),
                ('valid_before', models.DateTimeField()),
                ('is_ca', models.BooleanField(default=False)),
                ('is_root_ca', models.BooleanField(default=False)),
                ('revoked_date', models.DateTimeField(null=True)),
                ('cdp_info', models.JSONField(null=True)),
                ('auth_info', models.JSONField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('issuer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='django_pkiman.crt')),
            ],
            options={
                'verbose_name': 'Сертификат',
                'verbose_name_plural': 'Сертификаты',
            },
        ),
        migrations.CreateModel(
            name='CrlUpdateSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('dow', models.JSONField(verbose_name='дни недели')),
                ('std', models.TimeField(verbose_name='начало временного диапазона')),
                ('etd', models.TimeField(verbose_name='конец временного диапазона')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Расписание',
                'verbose_name_plural': 'Расписание',
                'ordering': ('name',),
                'indexes': [models.Index(fields=['is_active', 'std', 'etd'], name='crl_schedule_get_tasks_idx')],
            },
        ),
        migrations.CreateModel(
            name='Crl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint', models.CharField(max_length=64, unique=True)),
                ('file', models.FileField(upload_to=django_pkiman.models.get_upload_file_path)),
                ('crl_number', models.TextField(null=True)),
                ('last_update', models.DateTimeField()),
                ('next_update', models.DateTimeField()),
                ('revoked_count', models.IntegerField(default=0)),
                ('urls', models.CharField(blank=True, max_length=128)),
                ('active', models.BooleanField(default=False)),
                ('no_proxy', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('f_date', models.DateTimeField(null=True)),
                ('f_size', models.PositiveSmallIntegerField(null=True)),
                ('f_etag', models.CharField(max_length=128, null=True)),
                ('f_sync', models.DateTimeField(null=True)),
                ('issuer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='crl', to='django_pkiman.crt')),
                ('proxy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_pkiman.proxy')),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crl_list', to='django_pkiman.crlupdateschedule')),
            ],
            options={
                'verbose_name': 'Список отзыва',
                'verbose_name_plural': 'Списки отзыва',
                'ordering': ('issuer',),
            },
        ),
        migrations.AddIndex(
            model_name='crt',
            index=models.Index(fields=['subject_dn', 'subject_identifier'], name='crt_get_issuer_idx'),
        ),
        migrations.AddIndex(
            model_name='crt',
            index=models.Index(fields=['issuer_dn', 'issuer_identifier', 'issuer', 'is_root_ca'], name='crt_filter_orphans_idx'),
        ),
        migrations.AddIndex(
            model_name='crt',
            index=models.Index(fields=['subject_dn', 'subject_identifier', 'serial'], name='crl_get_issuer_crt'),
        ),
        migrations.AlterUniqueTogether(
            name='crt',
            unique_together={('issuer_dn', 'serial')},
        ),
    ]
