name: Run Python Linter and Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 django cryptography
      - name: Run linter
        run: flake8 --extend-ignore=E501,C901 pkiman
      - name: Run tests with pytest
        run: python manage.py test --noinput --keepdb --failfast